In [26]:
import numpy as np

In [30]:
array_3 = [[1,2,3,5,4],[6,7,8,5,3]]

In [31]:
array_4=np.array(array_3)

In [32]:
array_4

array([[1, 2, 3, 5, 4],
       [6, 7, 8, 5, 3]])

In [33]:
type(array_4)

numpy.ndarray

In [34]:
array_4.shape

(2, 5)

In [35]:
array_4.ndim

2

In [36]:
#Which of the following would extract all the rows of the first 3 columns in a 2D array?

In [51]:
array_4[ : , :3]

array([[1, 2, 3],
       [6, 7, 8]])

In [46]:
ar=[[11, 12, 13, 14],[21, 22, 23, 24],[31, 32, 33, 34]]

In [48]:
nr=np.array(ar)

In [62]:
print(nr[:,0])

[11 21 31]


In [66]:
print(nr[0][:])

[11 12 13 14]
