In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6]) #1 D Array

In [4]:
arr1[0]

1

In [6]:
arr1[-1]

6

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (1727085317.py, line 1)

In [10]:
np.array([[0,0,0],[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
zero_array=np.zeros((7,5))
print(zero_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
zero_array=np.zeros((3,5),dtype=int)
print(zero_array)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [14]:
#Ones Matrix
ones_array=np.ones((4,4),dtype=int)
print(ones_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
